#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  env NO_CHECKSUM=yes pkg ensure databases/redis # TODO 3.0.7 checksum mismatch
}

bootstrap
